services:
  fastapi:
    image: alifahadrajpoot/api:v2
    ports:
      - "8080:8080"  
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    volumes:
      - D:\dockerpractice\DockerDesktopWSL:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: deliverypizza275  
      PGDATA: /var/lib/postgresql/data/pgdata  

      
